// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addToFavoritesApiMicroservicesMicroserviceIdFavoritePost, createMemberApiMembersPost, createMicroserviceApiMicroservicesPost, createUserApiAdminUsersPost, deleteMicroserviceApiMicroservicesMicroserviceIdDelete, deleteUserApiAdminUsersUserIdDelete, loginApiAuthLoginPost, type Options, reassignMemberApiMembersMemberIdPatch, registerApiAuthRegisterPost, removeFromFavoritesApiMicroservicesMicroserviceIdFavoriteDelete, removeMemberApiMembersMemberIdDelete, searchMicroservicesApiMicroservicesGet, updateMicroserviceApiMicroservicesMicroserviceIdPatch } from '../sdk.gen';
import type { AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostError, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponse, CreateMemberApiMembersPostData, CreateMemberApiMembersPostError, CreateMemberApiMembersPostResponse, CreateMicroserviceApiMicroservicesPostData, CreateMicroserviceApiMicroservicesPostError, CreateMicroserviceApiMicroservicesPostResponse, CreateUserApiAdminUsersPostData, CreateUserApiAdminUsersPostError, CreateUserApiAdminUsersPostResponse, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteError, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponse, DeleteUserApiAdminUsersUserIdDeleteData, DeleteUserApiAdminUsersUserIdDeleteError, DeleteUserApiAdminUsersUserIdDeleteResponse, LoginApiAuthLoginPostData, LoginApiAuthLoginPostError, LoginApiAuthLoginPostResponse, ReassignMemberApiMembersMemberIdPatchData, ReassignMemberApiMembersMemberIdPatchError, ReassignMemberApiMembersMemberIdPatchResponse, RegisterApiAuthRegisterPostData, RegisterApiAuthRegisterPostError, RegisterApiAuthRegisterPostResponse, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteError, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponse, RemoveMemberApiMembersMemberIdDeleteData, RemoveMemberApiMembersMemberIdDeleteError, RemoveMemberApiMembersMemberIdDeleteResponse, SearchMicroservicesApiMicroservicesGetData, SearchMicroservicesApiMicroservicesGetError, SearchMicroservicesApiMicroservicesGetResponse, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchError, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponse } from '../types.gen';

/**
 * Register
 */
export const registerApiAuthRegisterPostMutation = (options?: Partial<Options<RegisterApiAuthRegisterPostData>>): UseMutationOptions<RegisterApiAuthRegisterPostResponse, RegisterApiAuthRegisterPostError, Options<RegisterApiAuthRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterApiAuthRegisterPostResponse, RegisterApiAuthRegisterPostError, Options<RegisterApiAuthRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerApiAuthRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginApiAuthLoginPostMutation = (options?: Partial<Options<LoginApiAuthLoginPostData>>): UseMutationOptions<LoginApiAuthLoginPostResponse, LoginApiAuthLoginPostError, Options<LoginApiAuthLoginPostData>> => {
    const mutationOptions: UseMutationOptions<LoginApiAuthLoginPostResponse, LoginApiAuthLoginPostError, Options<LoginApiAuthLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginApiAuthLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const searchMicroservicesApiMicroservicesGetQueryKey = (options?: Options<SearchMicroservicesApiMicroservicesGetData>) => createQueryKey('searchMicroservicesApiMicroservicesGet', options);

/**
 * Search Microservices
 */
export const searchMicroservicesApiMicroservicesGetOptions = (options?: Options<SearchMicroservicesApiMicroservicesGetData>) => queryOptions<SearchMicroservicesApiMicroservicesGetResponse, SearchMicroservicesApiMicroservicesGetError, SearchMicroservicesApiMicroservicesGetResponse, ReturnType<typeof searchMicroservicesApiMicroservicesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchMicroservicesApiMicroservicesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchMicroservicesApiMicroservicesGetQueryKey(options)
});

/**
 * Create Microservice
 */
export const createMicroserviceApiMicroservicesPostMutation = (options?: Partial<Options<CreateMicroserviceApiMicroservicesPostData>>): UseMutationOptions<CreateMicroserviceApiMicroservicesPostResponse, CreateMicroserviceApiMicroservicesPostError, Options<CreateMicroserviceApiMicroservicesPostData>> => {
    const mutationOptions: UseMutationOptions<CreateMicroserviceApiMicroservicesPostResponse, CreateMicroserviceApiMicroservicesPostError, Options<CreateMicroserviceApiMicroservicesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createMicroserviceApiMicroservicesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Microservice
 */
export const deleteMicroserviceApiMicroservicesMicroserviceIdDeleteMutation = (options?: Partial<Options<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData>>): UseMutationOptions<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponse, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteError, Options<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponse, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteError, Options<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteMicroserviceApiMicroservicesMicroserviceIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Microservice
 */
export const updateMicroserviceApiMicroservicesMicroserviceIdPatchMutation = (options?: Partial<Options<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData>>): UseMutationOptions<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponse, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchError, Options<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponse, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchError, Options<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMicroserviceApiMicroservicesMicroserviceIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove From Favorites
 *
 * Удаление микросервиса из избранного
 */
export const removeFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteMutation = (options?: Partial<Options<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData>>): UseMutationOptions<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponse, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteError, Options<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData>> => {
    const mutationOptions: UseMutationOptions<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponse, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteError, Options<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeFromFavoritesApiMicroservicesMicroserviceIdFavoriteDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add To Favorites
 */
export const addToFavoritesApiMicroservicesMicroserviceIdFavoritePostMutation = (options?: Partial<Options<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData>>): UseMutationOptions<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponse, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostError, Options<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData>> => {
    const mutationOptions: UseMutationOptions<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponse, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostError, Options<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addToFavoritesApiMicroservicesMicroserviceIdFavoritePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create User
 */
export const createUserApiAdminUsersPostMutation = (options?: Partial<Options<CreateUserApiAdminUsersPostData>>): UseMutationOptions<CreateUserApiAdminUsersPostResponse, CreateUserApiAdminUsersPostError, Options<CreateUserApiAdminUsersPostData>> => {
    const mutationOptions: UseMutationOptions<CreateUserApiAdminUsersPostResponse, CreateUserApiAdminUsersPostError, Options<CreateUserApiAdminUsersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUserApiAdminUsersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete User
 */
export const deleteUserApiAdminUsersUserIdDeleteMutation = (options?: Partial<Options<DeleteUserApiAdminUsersUserIdDeleteData>>): UseMutationOptions<DeleteUserApiAdminUsersUserIdDeleteResponse, DeleteUserApiAdminUsersUserIdDeleteError, Options<DeleteUserApiAdminUsersUserIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserApiAdminUsersUserIdDeleteResponse, DeleteUserApiAdminUsersUserIdDeleteError, Options<DeleteUserApiAdminUsersUserIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUserApiAdminUsersUserIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Member
 */
export const createMemberApiMembersPostMutation = (options?: Partial<Options<CreateMemberApiMembersPostData>>): UseMutationOptions<CreateMemberApiMembersPostResponse, CreateMemberApiMembersPostError, Options<CreateMemberApiMembersPostData>> => {
    const mutationOptions: UseMutationOptions<CreateMemberApiMembersPostResponse, CreateMemberApiMembersPostError, Options<CreateMemberApiMembersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createMemberApiMembersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove Member
 */
export const removeMemberApiMembersMemberIdDeleteMutation = (options?: Partial<Options<RemoveMemberApiMembersMemberIdDeleteData>>): UseMutationOptions<RemoveMemberApiMembersMemberIdDeleteResponse, RemoveMemberApiMembersMemberIdDeleteError, Options<RemoveMemberApiMembersMemberIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<RemoveMemberApiMembersMemberIdDeleteResponse, RemoveMemberApiMembersMemberIdDeleteError, Options<RemoveMemberApiMembersMemberIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeMemberApiMembersMemberIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reassign Member
 */
export const reassignMemberApiMembersMemberIdPatchMutation = (options?: Partial<Options<ReassignMemberApiMembersMemberIdPatchData>>): UseMutationOptions<ReassignMemberApiMembersMemberIdPatchResponse, ReassignMemberApiMembersMemberIdPatchError, Options<ReassignMemberApiMembersMemberIdPatchData>> => {
    const mutationOptions: UseMutationOptions<ReassignMemberApiMembersMemberIdPatchResponse, ReassignMemberApiMembersMemberIdPatchError, Options<ReassignMemberApiMembersMemberIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reassignMemberApiMembersMemberIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
