// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostErrors, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponses, CreateMemberApiMembersPostData, CreateMemberApiMembersPostErrors, CreateMemberApiMembersPostResponses, CreateMicroserviceApiMicroservicesPostData, CreateMicroserviceApiMicroservicesPostErrors, CreateMicroserviceApiMicroservicesPostResponses, CreateUserApiAdminUsersPostData, CreateUserApiAdminUsersPostErrors, CreateUserApiAdminUsersPostResponses, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteErrors, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponses, DeleteUserApiAdminUsersUserIdDeleteData, DeleteUserApiAdminUsersUserIdDeleteErrors, DeleteUserApiAdminUsersUserIdDeleteResponses, LoginApiAuthLoginPostData, LoginApiAuthLoginPostErrors, LoginApiAuthLoginPostResponses, ReassignMemberApiMembersMemberIdPatchData, ReassignMemberApiMembersMemberIdPatchErrors, ReassignMemberApiMembersMemberIdPatchResponses, RegisterApiAuthRegisterPostData, RegisterApiAuthRegisterPostErrors, RegisterApiAuthRegisterPostResponses, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteErrors, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponses, RemoveMemberApiMembersMemberIdDeleteData, RemoveMemberApiMembersMemberIdDeleteErrors, RemoveMemberApiMembersMemberIdDeleteResponses, SearchMicroservicesApiMicroservicesGetData, SearchMicroservicesApiMicroservicesGetErrors, SearchMicroservicesApiMicroservicesGetResponses, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchErrors, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register
 */
export const registerApiAuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiAuthRegisterPostData, ThrowOnError>) => (options.client ?? client).post<RegisterApiAuthRegisterPostResponses, RegisterApiAuthRegisterPostErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiAuthLoginPostResponses, LoginApiAuthLoginPostErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search Microservices
 */
export const searchMicroservicesApiMicroservicesGet = <ThrowOnError extends boolean = false>(options?: Options<SearchMicroservicesApiMicroservicesGetData, ThrowOnError>) => (options?.client ?? client).get<SearchMicroservicesApiMicroservicesGetResponses, SearchMicroservicesApiMicroservicesGetErrors, ThrowOnError>({ url: '/api/microservices', ...options });

/**
 * Create Microservice
 */
export const createMicroserviceApiMicroservicesPost = <ThrowOnError extends boolean = false>(options: Options<CreateMicroserviceApiMicroservicesPostData, ThrowOnError>) => (options.client ?? client).post<CreateMicroserviceApiMicroservicesPostResponses, CreateMicroserviceApiMicroservicesPostErrors, ThrowOnError>({
    url: '/api/microservices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Microservice
 */
export const deleteMicroserviceApiMicroservicesMicroserviceIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponses, DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteErrors, ThrowOnError>({ url: '/api/microservices/{microservice_id}', ...options });

/**
 * Update Microservice
 */
export const updateMicroserviceApiMicroservicesMicroserviceIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponses, UpdateMicroserviceApiMicroservicesMicroserviceIdPatchErrors, ThrowOnError>({
    url: '/api/microservices/{microservice_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove From Favorites
 *
 * Удаление микросервиса из избранного
 */
export const removeFromFavoritesApiMicroservicesMicroserviceIdFavoriteDelete = <ThrowOnError extends boolean = false>(options: Options<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData, ThrowOnError>) => (options.client ?? client).delete<RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponses, RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteErrors, ThrowOnError>({ url: '/api/microservices/{microservice_id}/favorite', ...options });

/**
 * Add To Favorites
 */
export const addToFavoritesApiMicroservicesMicroserviceIdFavoritePost = <ThrowOnError extends boolean = false>(options: Options<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData, ThrowOnError>) => (options.client ?? client).post<AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponses, AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostErrors, ThrowOnError>({ url: '/api/microservices/{microservice_id}/favorite', ...options });

/**
 * Create User
 */
export const createUserApiAdminUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserApiAdminUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserApiAdminUsersPostResponses, CreateUserApiAdminUsersPostErrors, ThrowOnError>({
    url: '/api/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User
 */
export const deleteUserApiAdminUsersUserIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteUserApiAdminUsersUserIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserApiAdminUsersUserIdDeleteResponses, DeleteUserApiAdminUsersUserIdDeleteErrors, ThrowOnError>({ url: '/api/admin/users/{user_id}', ...options });

/**
 * Create Member
 */
export const createMemberApiMembersPost = <ThrowOnError extends boolean = false>(options: Options<CreateMemberApiMembersPostData, ThrowOnError>) => (options.client ?? client).post<CreateMemberApiMembersPostResponses, CreateMemberApiMembersPostErrors, ThrowOnError>({
    url: '/api/members',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove Member
 */
export const removeMemberApiMembersMemberIdDelete = <ThrowOnError extends boolean = false>(options: Options<RemoveMemberApiMembersMemberIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<RemoveMemberApiMembersMemberIdDeleteResponses, RemoveMemberApiMembersMemberIdDeleteErrors, ThrowOnError>({ url: '/api/members/{member_id}', ...options });

/**
 * Reassign Member
 */
export const reassignMemberApiMembersMemberIdPatch = <ThrowOnError extends boolean = false>(options: Options<ReassignMemberApiMembersMemberIdPatchData, ThrowOnError>) => (options.client ?? client).patch<ReassignMemberApiMembersMemberIdPatchResponses, ReassignMemberApiMembersMemberIdPatchErrors, ThrowOnError>({
    url: '/api/members/{member_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
