// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CreateMemberRequest
 */
export type CreateMemberRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Microservice Id
     */
    microservice_id: string;
};

/**
 * CreateMemberResponse
 */
export type CreateMemberResponse = {
    /**
     * Member Id
     */
    member_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Microservice Name
     */
    microservice_name: string;
    role: RoleEnum;
    /**
     * Added At
     */
    added_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * CreateMicroserviceRequest
 */
export type CreateMicroserviceRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * CreateMicroserviceResponse
 */
export type CreateMicroserviceResponse = {
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status: MicroserviceStatusEnum;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    role: RoleEnum;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    role: RoleEnum;
    /**
     * Registered At
     */
    registered_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * DeleteMemberResponse
 */
export type DeleteMemberResponse = {
    /**
     * Member Id
     */
    member_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Microservice Name
     */
    microservice_name: string;
    role: RoleEnum;
    /**
     * Message
     */
    message?: string;
};

/**
 * DeleteMicroserviceResponse
 */
export type DeleteMicroserviceResponse = {
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * DeleteUserResponse
 */
export type DeleteUserResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * FavoriteRemoveResponse
 */
export type FavoriteRemoveResponse = {
    /**
     * Message
     */
    message?: string;
};

/**
 * FavoriteResponse
 */
export type FavoriteResponse = {
    /**
     * Favorite Id
     */
    favorite_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Microservice Name
     */
    microservice_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * MicroserviceListResponse
 */
export type MicroserviceListResponse = {
    /**
     * Microservices
     */
    microservices: Array<MicroserviceSearchResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * MicroserviceSearchResponse
 */
export type MicroserviceSearchResponse = {
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status: MicroserviceStatusEnum;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * MicroserviceStatusEnum
 */
export type MicroserviceStatusEnum = 'active' | 'inactive';

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * RegisterResponse
 */
export type RegisterResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Registered At
     */
    registered_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * RoleEnum
 */
export type RoleEnum = 'lead' | 'developer' | 'user' | 'moderator';

/**
 * UpdateMemberRequest
 */
export type UpdateMemberRequest = {
    /**
     * Microservice Id
     */
    microservice_id: string;
};

/**
 * UpdateMemberResponse
 */
export type UpdateMemberResponse = {
    /**
     * Member Id
     */
    member_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Microservice Name
     */
    microservice_name: string;
    role: RoleEnum;
    /**
     * Message
     */
    message?: string;
};

/**
 * UpdateMicroserviceRequest
 */
export type UpdateMicroserviceRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    status?: MicroserviceStatusEnum | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
};

/**
 * UpdateMicroserviceResponse
 */
export type UpdateMicroserviceResponse = {
    /**
     * Microservice Id
     */
    microservice_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    status: MicroserviceStatusEnum;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Message
     */
    message?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type RegisterApiAuthRegisterPostData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: RegisterResponse;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type SearchMicroservicesApiMicroservicesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         *
         * Название микросервиса для поиска
         */
        name?: string | null;
    };
    url: '/api/microservices';
};

export type SearchMicroservicesApiMicroservicesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchMicroservicesApiMicroservicesGetError = SearchMicroservicesApiMicroservicesGetErrors[keyof SearchMicroservicesApiMicroservicesGetErrors];

export type SearchMicroservicesApiMicroservicesGetResponses = {
    /**
     * Successful Response
     */
    200: MicroserviceListResponse;
};

export type SearchMicroservicesApiMicroservicesGetResponse = SearchMicroservicesApiMicroservicesGetResponses[keyof SearchMicroservicesApiMicroservicesGetResponses];

export type CreateMicroserviceApiMicroservicesPostData = {
    body: CreateMicroserviceRequest;
    path?: never;
    query?: never;
    url: '/api/microservices';
};

export type CreateMicroserviceApiMicroservicesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMicroserviceApiMicroservicesPostError = CreateMicroserviceApiMicroservicesPostErrors[keyof CreateMicroserviceApiMicroservicesPostErrors];

export type CreateMicroserviceApiMicroservicesPostResponses = {
    /**
     * Successful Response
     */
    200: CreateMicroserviceResponse;
};

export type CreateMicroserviceApiMicroservicesPostResponse = CreateMicroserviceApiMicroservicesPostResponses[keyof CreateMicroserviceApiMicroservicesPostResponses];

export type DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Microservice Id
         */
        microservice_id: string;
    };
    query?: never;
    url: '/api/microservices/{microservice_id}';
};

export type DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteError = DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteErrors[keyof DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteErrors];

export type DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteMicroserviceResponse;
};

export type DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponse = DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponses[keyof DeleteMicroserviceApiMicroservicesMicroserviceIdDeleteResponses];

export type UpdateMicroserviceApiMicroservicesMicroserviceIdPatchData = {
    body: UpdateMicroserviceRequest;
    path: {
        /**
         * Microservice Id
         */
        microservice_id: string;
    };
    query?: never;
    url: '/api/microservices/{microservice_id}';
};

export type UpdateMicroserviceApiMicroservicesMicroserviceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMicroserviceApiMicroservicesMicroserviceIdPatchError = UpdateMicroserviceApiMicroservicesMicroserviceIdPatchErrors[keyof UpdateMicroserviceApiMicroservicesMicroserviceIdPatchErrors];

export type UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UpdateMicroserviceResponse;
};

export type UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponse = UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponses[keyof UpdateMicroserviceApiMicroservicesMicroserviceIdPatchResponses];

export type RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteData = {
    body?: never;
    path: {
        /**
         * Microservice Id
         */
        microservice_id: string;
    };
    query?: never;
    url: '/api/microservices/{microservice_id}/favorite';
};

export type RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteError = RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteErrors[keyof RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteErrors];

export type RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponses = {
    /**
     * Successful Response
     */
    200: FavoriteRemoveResponse;
};

export type RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponse = RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponses[keyof RemoveFromFavoritesApiMicroservicesMicroserviceIdFavoriteDeleteResponses];

export type AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostData = {
    body?: never;
    path: {
        /**
         * Microservice Id
         */
        microservice_id: string;
    };
    query?: never;
    url: '/api/microservices/{microservice_id}/favorite';
};

export type AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostError = AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostErrors[keyof AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostErrors];

export type AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponses = {
    /**
     * Successful Response
     */
    200: FavoriteResponse;
};

export type AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponse = AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponses[keyof AddToFavoritesApiMicroservicesMicroserviceIdFavoritePostResponses];

export type CreateUserApiAdminUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/admin/users';
};

export type CreateUserApiAdminUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiAdminUsersPostError = CreateUserApiAdminUsersPostErrors[keyof CreateUserApiAdminUsersPostErrors];

export type CreateUserApiAdminUsersPostResponses = {
    /**
     * Successful Response
     */
    200: CreateUserResponse;
};

export type CreateUserApiAdminUsersPostResponse = CreateUserApiAdminUsersPostResponses[keyof CreateUserApiAdminUsersPostResponses];

export type DeleteUserApiAdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/admin/users/{user_id}';
};

export type DeleteUserApiAdminUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiAdminUsersUserIdDeleteError = DeleteUserApiAdminUsersUserIdDeleteErrors[keyof DeleteUserApiAdminUsersUserIdDeleteErrors];

export type DeleteUserApiAdminUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteUserResponse;
};

export type DeleteUserApiAdminUsersUserIdDeleteResponse = DeleteUserApiAdminUsersUserIdDeleteResponses[keyof DeleteUserApiAdminUsersUserIdDeleteResponses];

export type CreateMemberApiMembersPostData = {
    body: CreateMemberRequest;
    path?: never;
    query?: never;
    url: '/api/members';
};

export type CreateMemberApiMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMemberApiMembersPostError = CreateMemberApiMembersPostErrors[keyof CreateMemberApiMembersPostErrors];

export type CreateMemberApiMembersPostResponses = {
    /**
     * Successful Response
     */
    200: CreateMemberResponse;
};

export type CreateMemberApiMembersPostResponse = CreateMemberApiMembersPostResponses[keyof CreateMemberApiMembersPostResponses];

export type RemoveMemberApiMembersMemberIdDeleteData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/members/{member_id}';
};

export type RemoveMemberApiMembersMemberIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberApiMembersMemberIdDeleteError = RemoveMemberApiMembersMemberIdDeleteErrors[keyof RemoveMemberApiMembersMemberIdDeleteErrors];

export type RemoveMemberApiMembersMemberIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteMemberResponse;
};

export type RemoveMemberApiMembersMemberIdDeleteResponse = RemoveMemberApiMembersMemberIdDeleteResponses[keyof RemoveMemberApiMembersMemberIdDeleteResponses];

export type ReassignMemberApiMembersMemberIdPatchData = {
    body: UpdateMemberRequest;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/members/{member_id}';
};

export type ReassignMemberApiMembersMemberIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReassignMemberApiMembersMemberIdPatchError = ReassignMemberApiMembersMemberIdPatchErrors[keyof ReassignMemberApiMembersMemberIdPatchErrors];

export type ReassignMemberApiMembersMemberIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UpdateMemberResponse;
};

export type ReassignMemberApiMembersMemberIdPatchResponse = ReassignMemberApiMembersMemberIdPatchResponses[keyof ReassignMemberApiMembersMemberIdPatchResponses];
